name: CustomStaffList
version: 2.1
description: Simple way to display lists of players on the server
depend: [StBukkitLib]
softdepend: [VanishNoPacket]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.customstafflist.CustomStaffList
commands:
  customstafflist:
    description: 'Base plugin command'