name: ${project.name}
version: ${project.version}
description: Simple way to display lists of players on the server
depend: []
softdepend: [VanishNoPacket, Vault]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.customuserlist.CustomUserList
commands:
  customuserlist:
    description: 'Base plugin command'